version: "3"
services:
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/
    environment:
      # Update environment variables for database connection
      DB_HOST: "database-1.chgcawess2vp.us-west-2.rds.amazonaws.com"
      DB_DATABASE: "mydb"
      DB_USER: "admin"
      DB_PASSWORD: "passwd"

  apache:
    build: './apache/'
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/
    environment:
      # Update environment variables for database connection
      DB_HOST: "database-1.chgcawess2vp.us-west-2.rds.amazonaws.com"
      DB_DATABASE: "mydb"
      DB_USER: "admin"
      DB_PASSWORD: "mypassword"

volumes:
  db_data: {}  # This volume is no longer needed if you're not using the local MySQL container
