version: "3.8"

services:
  php-backend:
    build: './php/'
    container_name: php-backend
    volumes:
      - ./public:/var/www/html/
      # - ./public/dump:/docker-entrypoint-initdb.d/  # Directory for initial SQL scripts
    environment:
      # Update MySQL connection details for RDS
      environment:
        MYSQL_HOST: "database-1-instance-1.c3qw4u6g6zrr.ap-northeast-1.rds.amazonaws.com"
        MYSQL_PORT: "3306"
        MYSQL_DATABASE: "mydb"
        MYSQL_USER: "user1"
        MYSQL_PASSWORD: "mypassword"
    ports:
      - "9000:9000"

  apache:
    build: './apache/'
    depends_on:
      - php-backend
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/
    environment:
      MYSQL_HOST: "database-1-instance-1.c3qw4u6g6zrr.ap-northeast-1.rds.amazonaws.com"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "mypassword"



# No MySQL service since you're using RDS

volumes:
  db_data: {}  # Defined, but not used since we're not running a MySQL container
