version: "3"
services:
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/

  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "9000:80"
    volumes:
      - ./public:/var/www/html/
  
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./public/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_HOST: "database-1.chgcawess2vp.us-west-2.rds.amazonaws.com"
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "passwd"

volumes:
  db_data:
